FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# bookstore-rails-api

this REST api alows to manage database resources. a signed user can: add, remove, list and update books as well as select a favourite book.

## signup user [/signup]

### signup?  [POST]

+ response 201

    + Headers

            Cache-Control: max-age=0, private, must-revalidate
            Content-Type: application/json; charset=utf-8
            ETag: W/"4145e893615ab6e5eeb74afba5c37744"
            Referrer-Policy: strict-origin-when-cross-origin
            Transfer-Encoding: chunked
            X-Content-Type-Options: nosniff
            X-Download-Options: noopen
            X-Frame-Options: SAMEORIGIN
            X-Permitted-Cross-Domain-Policies: none
            X-Request-Id: c1141ac6-f541-4269-b375-a02493396e28
            X-Runtime: 0.892736
            X-XSS-Protection: 1; mode=block

    + Body

            {
                "auth_token": "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE1OTkyMjc0Mzl9.MPcxrXofsMXpTce9yDnC_wCnf4J5XIgAy9k_jeZtdNg",
                "message": "user created successfully"
            }