name: Linters

on: pull_request

jobs:
  rubocop:
    name: Rubocop
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: Setup Rubocop
        run: |
          gem install --no-document rubocop:'~>0.81.0' # https://docs.rubocop.org/en/stable/installation/
          [ -f .rubocop.yml ]
      - name: Rubocop Report
        run: rubocop --color